In [2]:
from bs4 import BeautifulSoup as soup
import requests
import numpy as np
import time
import pandas as pd
from splinter import Browser
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import Select
import plotly.express as px
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot
import cufflinks as cf
import math

In [24]:
df = pd.read_csv("export data year,HSCode, Country wise")

In [25]:
df

,Unnamed: 0,HSCode,Commodity,Value_of_Export,Country,Year
0,0,2023000,"BONELESS MEAT OF BOVINE ANIMALS , FROZEN",229.02,AFGHANISTAN TIS,2019-2020
1,1,2061000,"EDBL OFFAL OF BOVINE ANMLS,FRSH/CHILLED",NaN,AFGHANISTAN TIS,2019-2020
2,2,2062200,"EDIBLE LIVERS OF BOVINE ANIMALS, FROZEN",613.04,AFGHANISTAN TIS,2019-2020
3,3,2062900,"OTHR EDIBLE OFFAL OF BOVINE ANIMALS,FROZEN",910.99,AFGHANISTAN TIS,2019-2020
4,4,3024700,SWORD FISH FRESH OR CHILLED,NaN,AFGHANISTAN TIS,2019-2020
...,...,...,...,...,...,...
7965811,7965811,99919003,*ARTWARE OF ALUMINIUM,NaN,ZIMBABWE,1997-1998
7965812,7965812,99919015,"*PAPIER MACHE ARTCLS,AS ARTWARE",NaN,ZIMBABWE,1997-1998
7965813,7965813,99919029,"*OTHER,AS ARTWARE",8.69,ZIMBABWE,1997-1998
7965814,7965814,99930001,*SAMPLES,2.57,ZIMBABWE,1997-1998
7965815,7965815,99930009,*SPECIAL TRANSACTIONS N.E.S.,14.58,ZIMBABWE,1997-1998

In [26]:
df.replace(847150,84715000,inplace = True)

In [27]:
df['HSCode']=df['HSCode'].apply(lambda x: '{0:0>8}'.format(x))

In [28]:
df['2HSCode']=df['HSCode'].str[:2]
df['4HSCode']=df['HSCode'].str[:4]
df['6HSCode']=df['HSCode'].str[:6]

In [29]:
df['Commodity'] = df['Commodity'].str.strip("*")

In [31]:
df['Value_of_Export'] = df['Value_of_Export'].fillna(0)

In [33]:
df.drop(['Unnamed: 0'],axis=1,inplace=True)

In [34]:
df

,HSCode,Commodity,Value_of_Export,Country,Year,2HSCode,4HSCode,6HSCode
0,02023000,"BONELESS MEAT OF BOVINE ANIMALS , FROZEN",229.02,AFGHANISTAN TIS,2019-2020,02,0202,020230
1,02061000,"EDBL OFFAL OF BOVINE ANMLS,FRSH/CHILLED",0.00,AFGHANISTAN TIS,2019-2020,02,0206,020610
2,02062200,"EDIBLE LIVERS OF BOVINE ANIMALS, FROZEN",613.04,AFGHANISTAN TIS,2019-2020,02,0206,020622
3,02062900,"OTHR EDIBLE OFFAL OF BOVINE ANIMALS,FROZEN",910.99,AFGHANISTAN TIS,2019-2020,02,0206,020629
4,03024700,SWORD FISH FRESH OR CHILLED,0.00,AFGHANISTAN TIS,2019-2020,03,0302,030247
...,...,...,...,...,...,...,...,...
7965811,99919003,ARTWARE OF ALUMINIUM,0.00,ZIMBABWE,1997-1998,99,9991,999190
7965812,99919015,"PAPIER MACHE ARTCLS,AS ARTWARE",0.00,ZIMBABWE,1997-1998,99,9991,999190
7965813,99919029,"OTHER,AS ARTWARE",8.69,ZIMBABWE,1997-1998,99,9991,999190
7965814,99930001,SAMPLES,2.57,ZIMBABWE,1997-1998,99,9993,999300
7965815,99930009,SPECIAL TRANSACTIONS N.E.S.,14.58,ZIMBABWE,1997-1998,99,9993,999300

In [ ]:
df.to_csv('Export_Clean')